default_stages: [commit, push]
files: ''
exclude: '^\.logs/'
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
        name: Validate YAML syntax
      - id: check-json
        name: Validate JSON syntax
        exclude: ^\.vscode/
      - id: check-toml
        name: Validate TOML syntax
      - id: fix-byte-order-marker
        name: Remove BOM
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Fix End-of-File blank lines
        exclude: ^(LICENSE|requirements\.txt)$
      - id: requirements-txt-fixer
        name: Sort requirements file

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade - Upgrade Python code to the latest standard
        entry: poetry run pyupgrade --py{{ cookiecutter.minimum_python_version.replace('.', '') }}-plus
        types: [python]
        language: system
        files: ^src/

      - id: isort
        name: isort - reorder Python imports
        entry: poetry run isort --settings-path pyproject.toml
        types: [python]
        language: system
        require_serial: true

      - id: black
        name: black - reformat Python code
        entry: poetry run black --config pyproject.toml
        types: [python]
        language: system
        require_serial: true

      - id: pylint
        name: pylint
        entry: poetry run pylint
        types: [python]
        language: system
        require_serial: true

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.3
    hooks:
      - id: bandit
        language_version: python3
        exclude: ^tests/
        args:
          - -s
          - B101,B603

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: ^build/
        args: [--config, setup.cfg]
