# This file contains values from Cookiecutter

default_context:
  project_name: "{{ cookiecutter.project_name }}"
  project_description: "{{ cookiecutter.project_description }}"
  organization: "{{ cookiecutter.organization }}"
  license: "{{ cookiecutter.license }}"
  python_version: {{ cookiecutter.minimum_python_version }}
  github_username: "{{ cookiecutter.github_username }}"
  email: "{{ cookiecutter.email }}"
  version: "{{ cookiecutter.version }}"
  line_length: "{{ cookiecutter.line_length }}"
  create_example_template: "{{ cookiecutter.create_example_template }}"
